trigger:
  - main

variables:
  - group: PlatformChallenge # Create this variable group in Azure DevOps with sqlAdminLogin and sqlAdminPassword
  - name: azureSubscription
    value: '7d14f8f4-7499-4198-81df-58f5432cb5a0'
  - name: resourceGroupName
    value: 'SamuelB'
  - name: location
    value: 'eastus2'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep build --file infrastructure/bicep/main.bicep

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureSubscription)
        subscriptionId: $(azureSubscription)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'infrastructure/bicep/main.bicep'
        overrideParameters: >
          -sqlAdminLogin "$(sqlAdminLogin)"
          -sqlAdminPassword "$(sqlAdminPassword)"
          -location "$(location)"
        deploymentMode: 'Incremental'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: 'app-prod'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto' 